language: python
sudo: true
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"

before_install:
  #- sudo apt-get -qq update
  #- sudo apt-get install -y libxml2-dev
  #- sudo apt-get install -yqq imagemagick

addons:
  apt:
    packages:
    - imagemagick


install:
  - pip install -r requirements.txt
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "pip install --no-deps -U ."

script:
  - "firefox --version"
  - "pushd atest/acceptance"
  - "python -m robot.run  -b debug.log -e TODO -e WIN -r none -l none ."
  - "cat debug.log"
env:
  matrix:
  - BROWSER=firefox

