language: python
sudo: required
dist: bionic
services:
  - xvfb
env:
  global:
    - GRID=False
    - PYPY=False
    - BROWSER=gc
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - imagemagick
before_install:
  - CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - echo $CDVERSION
  - wget --no-verbose http://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/

matrix:
  include:
    - python: "3.7"
      env:
        - BROWSER=headlesschrome
        - SELENIUM=3.141.0
        - ROBOTFRAMEWORK=3.1.2
        - ROBOT_OPTIONS=--dotted
        - INTERPRETER=python3

install:
  - pip install -r requirements.txt
  

before_script:
  - if [ "$PYPY" == "True" ]; then
      sudo snap install pypy3 --classic;
      sudo apt-get install virtualenv;
      virtualenv -p pypy3 pypy3ve;
      . pypy3ve/bin/activate;
    fi
  - echo $INTERPRETER
  - $INTERPRETER --version
  - $INTERPRETER -m pip install robotframework==$ROBOTFRAMEWORK
  - $INTERPRETER -m pip install -r requirements.txt;
  - $INTERPRETER -m pip install .
  - if [ "$GRID" == "True" ]; then
      wget --output-document=./selenium-server-standalone.jar http://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar;
      sudo chmod u+x ./selenium-server-standalone.jar;
    fi

script:
  - "pushd atest/acceptance"
  - "python -m robot.run  -b debug.log -e TODO -e WIN -r none -l none ."
  - "cat debug.log"


