[tool.robotidy]
configure = []
diff = true
overwrite = true
transform = [
  "AddMissingEnd",
  "AlignSettingsSection",
  "AlignTestCases",
  "AlignVariablesSection",
  "DiscardEmptySections",
  "InlineIf",
  "MergeAndOrderSections",
  "NormalizeAssignments",
  "NormalizeSectionHeaderName",
  "NormalizeSeparators",
  "NormalizeSettingName",
  "NormalizeNewLines",
  "NormalizeTags:enabled=True:case=uppercase",
  "OrderSettings",
  "OrderTags:enabled=True",
  "RemoveEmptySettings",
  "RenameKeywords:enabled=True",
  "RenameTestCases:enabled=True",
  "ReplaceBreakContinue",
  "ReplaceReturns",
  "ReplaceRunKeywordIf",
  "SmartSortKeywords:enabled=True",
]

[tool.robocop]
configure = [
  "line-too-long:line_length:160",
  "too-long-test-case:max_len:40",
  "too-many-calls-in-test-case:max_calls:20",
]
exclude = ["keyword-after-return", "*doc*"]
format = "{source}:{line}:{col} [{severity}] {rule_id} {desc} (name)"
reports = [
  "all",
]
threshold = "I"
